FROM --platform=$BUILDPLATFORM python:3.9-alpine3.15

LABEL MAINTAINER "Prashant Shahi <me@prashantshahi.dev>"

RUN pip install --upgrade pip

RUN adduser -D appuser
USER appuser
WORKDIR /home/appuser

ENV PATH="/home/appuser/.local/bin:${PATH}"

COPY --chown=appuser:appuser requirements.txt requirements.txt
RUN pip install --user -r requirements.txt

COPY --chown=appuser:appuser . .

ENTRYPOINT ["python"]

CMD ["app.py"]
